require("typescript-tools").setup {
    on_attach = function ()
        if vim.lsp.inlay_hint and vim.lsp.inlay_hint.enable then
            vim.lsp.inlay_hint.enable(true, bufnr)
        end
    end,
    settings = {
        separate_diagnostic_server = true,
        publish_diagnostic_on = "insert_leave",
        -- expose_as_code_action = { "all" },
        tsserver_path = nil,
        tsserver_plugins = {},
        tsserver_max_memory = "auto",
        tsserver_format_options = {
            allowIncompleteCompletions = true,
            allowRenameOfImportPath = true,
            insertSpaceAfterCommaDelimiter = true,
            insertSpaceAfterSemicolonInForStatements = true,
            insertSpaceBeforeAndAfterBinaryOperators = true,
            insertSpaceAfterConstructor = false,
            insertSpaceAfterKeywordsInControlFlowStatements = true,
            insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
            insertSpaceAfterOpeningAndBeforeClosingEmptyBraces = false,
            insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = false,
            insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = false,
            insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true,
            insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces = false,
            insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = true,
            insertSpaceAfterTypeAssertion = true,
            insertSpaceBeforeFunctionParenthesis = false,
            placeOpenBraceOnNewLineForFunctions = true,
            placeOpenBraceOnNewLineForControlBlocks = true,
            insertSpaceBeforeTypeAnnotation = true,
            semicolons = true,
        },
        tsserver_file_preferences = {
            disableSuggestions = false,
            quotePreference = "single",
            includeCompletionsForModuleExports = true,
            includeCompletionsForImportStatements = true,
            includeCompletionsWithSnippetText = true,
            includeCompletionsWithInsertText = true,
            includeAutomaticOptionalChainCompletions = true,
            includeCompletionsWithClassMemberSnippets = true,
            includeCompletionsWithObjectLiteralMethodSnippets = true,
            useLabelDetailsInCompletionEntries = true,
            allowIncompleteCompletions = true,
            importModuleSpecifierPreference = "relative",
            importModuleSpecifierEnding = "auto",
            allowTextChangesInNewFiles = true,
            lazyConfiguredProjectsFromExternalProject = true,
            providePrefixAndSuffixTextForRename = true,
            provideRefactorNotApplicableReason = true,
            allowRenameOfImportPath = true,
            includePackageJsonAutoImports = "on",
            jsxAttributeCompletionStyle = "braces",
            displayPartsForJSDoc = true,
            generateReturnInDocTemplate = true,
            includeInlayParameterNameHints = "all",
            includeInlayParameterNameHintsWhenArgumentMatchesName = true,
            includeInlayFunctionParameterTypeHints = true,
            includeInlayVariableTypeHints = true,
            includeInlayVariableTypeHintsWhenTypeMatchesName = true,
            includeInlayPropertyDeclarationTypeHints = true,
            includeInlayFunctionLikeReturnTypeHints = true,
            includeInlayEnumMemberValueHints = true,
            organizeImportsIgnoreCase = false,
        },
        tsserver_locale = "en",
        complete_function_calls = true,
        include_completions_with_insert_text = true,
        code_lens = "all",
        disable_member_code_lens = true,
        jsx_close_tag = {
            enable = true,
            filetypes = { "javascriptreact", "typescriptreact" },
        }
    },
}
